[package]
name = "rust-pi"
version = "0.1.0"
edition = "2021"

[dependencies]
tinyrand = "0.5.0"
statrs = "0.18.0"
clap = { version =  "4.5.42", features = ["derive"] }

[dev-dependencies]
assert_float_eq = "1.1.4"
